[app]
title = Accessibility Companion
package.name = accessibilitycompanion
package.domain = org.accessibility
source.dir = .
source.exts = py,png,jpg,kv,atlas
version = 1.0
requirements = python3,kivy
orientation = portrait
osx.python_version = 3
osx.kivy_version = 1.9.1
fullscreen = 0
android.permissions = INTERNET
android.api = 33
android.min_api = 21
android.sdk = 30
android.ndk = 25b
android.gradle_dependencies = 
android.skip_update = False
android.accept_sdk_license = True
